### ISSUE TITLE
TODO: Adatbázis

### ISSUE THREAD

**Issue by lipcseiadam** [Zentrom/kartyajatek#11]
A data fájlban tárolt adatokkal a későbiekben nehéz lesz játszadozni, szertintem egyszerűbb lenne valami gagyi adatbázist alárakni helyette (1-2 táblás max)

**Comment by Zentrom** [comment]
ha értenék hozzá :D

**Comment by lipcseiadam** [comment]
Ha sikerül eletreketenem a netbeansben a java dbt akkor megcsinálom, csak bugos es nem tud kapcsolodni

**Comment by Zentrom** [comment]
Okés,addig marad a data file. Igazábol csak azért csináltam azt, hogy legyen valami.

**Comment by lipcseiadam** [comment]
mivel 1 tábla kellene és a javadb az istenért sem akar életre kelni lezárom az issuet
